import { useState } from 'react';
import { Check,RefreshCw,RotateCcw,UserCheck,X } from 'lucide-react';
import { salesRequest } from '../lib/sales';
import type { OwnerSales,SalesCredit } from '../lib/sales';
import { payoutCurrency as currency } from '../lib/calculations';

export function OwnerSalesPanel({ data, section, onRefresh }: { data?: OwnerSales; section: "people" | "review"; onRefresh: () => Promise<void> }) {
  const [error,setError]=useState('');const [working,setWorking]=useState(false);
  const reload=onRefresh;
  async function run(path:string,body:unknown){setWorking(true);try{await salesRequest(path,'PATCH',body);await reload();}catch(e){setError(e instanceof Error?e.message:'Unable to save.');}finally{setWorking(false);}}
  async function review(c:SalesCredit,decision:string){const ownerNote=decision==='correct'?window.prompt('Why should this commission be recalculated and returned to review?'):decision==='rejected'?window.prompt('Reason for rejecting this commission:'):'';if(ownerNote===null)return;setWorking(true);try{await salesRequest(`/api/owner/sales-commissions/${c.id}/review`,'POST',{decision,ownerNote});await reload();}catch(e){setError(e instanceof Error?e.message:'Unable to review.');}finally{setWorking(false);}}
  function renderCredits(credits: SalesCredit[]) { return credits.map(c => <article key={c.id} className="rounded-lg border border-slate-200 bg-white p-4 dark:border-slate-700 dark:bg-slate-900"><div className="flex flex-wrap justify-between gap-3"><div><strong>{c.salesmanName} · {c.customerName}</strong><p className="mt-1 text-sm">{c.jobDate} · {currency.format(c.servicePrice)} × 20% = {currency.format(c.amount)} · <span className="capitalize">{c.status}</span></p>{c.ownerNote&&<p className="mt-1 text-sm text-slate-500">{c.ownerNote}</p>}{c.workerPending&&<p className="mt-2 text-sm text-amber-600">Review worker earnings first.</p>}{['approved','paid'].includes(c.status)&&c.currentServicePrice!==c.servicePrice&&<p className="mt-2 text-sm text-amber-600">Current service price: {currency.format(c.currentServicePrice)}. Approved amount remains locked.</p>}</div><div className="flex flex-wrap items-start gap-2">{c.status==='pending'&&<><button className="text-button gap-2" disabled={working||c.workerPending} onClick={()=>void review(c,'rejected')}><X size={15}/>Reject</button><button className="primary-button gap-2" disabled={working||c.workerPending} onClick={()=>void review(c,'approved')}><Check size={15}/>Approve</button></>}{['approved','rejected'].includes(c.status)&&!c.payrollLinked&&<button className="text-button gap-2" disabled={working} onClick={()=>void review(c,'correct')}><RotateCcw size={15}/>Return to review</button>}{c.payrollLinked&&<span className="text-xs text-slate-500">Locked in contractor payroll</span>}</div></div></article>); }
  return <section className="space-y-4 border-b border-slate-200 py-5 dark:border-slate-800"><div className="flex justify-between items-center gap-3"><h2 className="text-xl font-bold">{section === "people" ? "Sales accounts" : "Sales commission review"}</h2><button className="icon-button" title="Refresh sales team" aria-label="Refresh sales team" disabled={working} onClick={()=>void reload().catch(()=>undefined)}><RefreshCw size={18}/></button></div>{error&&<p role="alert" className="rounded-lg bg-rose-100 p-3 text-sm text-rose-700">{error}</p>}{section === "people" && <><div className="grid gap-3 lg:grid-cols-2">{data?.salesmen.map(person=><article key={person.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-slate-200 bg-white p-4 dark:border-slate-700 dark:bg-slate-900"><div className="min-w-0"><strong className="block break-words">{person.name}</strong><p className="text-sm break-all text-slate-500">{person.email}</p><p className="mt-1 text-sm">20% sales commission · {person.active?'Active':'Inactive'}</p></div><button className="text-button gap-2" disabled={working} onClick={()=>void run(`/api/owner/salesmen/${person.id}`,{active:!person.active})}><UserCheck size={16}/>{person.active?'Deactivate':'Activate'}</button></article>)}</div>{data&&!data.salesmen.length&&<p className="text-sm text-slate-500">No salesman accounts yet.</p>}</>}{section === "review" && <><div className="space-y-3">{renderCredits((data?.commissions ?? []).filter(c => c.status === "pending"))}</div>{data&&!data.commissions.some(c=>c.status==='pending')&&<p className="text-sm text-slate-500">No sales commissions awaiting review.</p>}{data?.commissions.some(c => ["approved","rejected","paid"].includes(c.status)) && <details><summary className="cursor-pointer py-3 text-sm font-semibold">Sales commission history</summary><div className="mt-2 space-y-3">{renderCredits(data.commissions.filter(c => ["approved","rejected","paid"].includes(c.status)))}</div></details>}</>}</section>;
}
