import { lazy, Suspense, useCallback, useEffect, useMemo, useState } from 'react';
import type { FormEvent } from 'react';
import { BadgeDollarSign, Bell, BriefcaseBusiness, CalendarClock, Check, Home, Mail, MapPinned, Menu, Pencil, Phone, Plus, RefreshCw, Save, Search, X } from 'lucide-react';
import { useAuth } from '../lib/authContext';
import { currency,isoToday } from '../lib/calculations';
import { createSolicitation,deleteSolicitation,loadReadNotificationKeys,markNotificationsRead,saveSolicitationPatch } from '../lib/api';
import { salesRequest } from '../lib/sales';
import { createSalesmanPreview, mergePreviewMapHistory, removePreviewSolicitation, savePreviewSalesBooking, savePreviewSalesLead, savePreviewSolicitation } from '../lib/salesmanPreview';
import type { SalesBooking,SalesMapHistory,SalesNotification,SalesWorkspace } from '../lib/sales';
import type { Job,Lead } from '../types/business';
import { ProfileMenu } from './ProfileMenu';
import { EmployeePayrollStatements } from './EmployeePayrollStatements';
import { loadThemePreference,saveThemePreference,themeIsDark } from '../lib/themePreference';

const BusinessMap=lazy(()=>import('./BusinessMap').then(module=>({default:module.BusinessMap})));
type Tab='dashboard'|'map'|'jobs'|'leads'|'earnings';
const tabs=[{id:'dashboard',name:'Dashboard',icon:Home},{id:'map',name:'Map',icon:MapPinned},{id:'jobs',name:'My Jobs',icon:BriefcaseBusiness},{id:'leads',name:'Leads',icon:CalendarClock},{id:'earnings',name:'My Earnings',icon:BadgeDollarSign}] as const;
const input='mt-2 block w-full min-w-0 max-w-full rounded-lg border border-slate-300 bg-white px-3 py-3 text-base font-normal text-ink dark:border-slate-700 dark:bg-slate-950 dark:text-white';
const statusClass='rounded-md bg-mist px-2 py-1 text-xs font-semibold capitalize text-lagoon dark:bg-cyan-500/15 dark:text-cyan-200';
const formatRate=(rate:number)=>`${Math.round(rate*10000)/100}%`;
function canEdit(job:Job){const now=new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).format(new Date()).replace(' ','T');return job.status==='scheduled'&&`${job.date}T${job.time}:00`>now;}

export function SalesmanWorkspace({preview=false,onExitPreview}:{preview?:boolean;onExitPreview?:()=>void}){
  const {user}=useAuth();const [tab,setTab]=useState<Tab>('dashboard');const [menu,setMenu]=useState(false);
  const isPreview=preview&&user.role==='owner';
  const [data,setData]=useState<SalesWorkspace|undefined>(()=>isPreview?createSalesmanPreview(isoToday()):undefined);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const [search,setSearch]=useState('');const [status,setStatus]=useState('all');
  const [booking,setBooking]=useState<Partial<SalesBooking>|null>(null);const [editing,setEditing]=useState<Job|null>(null);
  const [lead,setLead]=useState<Lead|null>(null);const [focus,setFocus]=useState<{jobId:string;requestId:number}|null>(null);
  const [theme,setTheme]=useState(()=>loadThemePreference(user.id));
  const refresh=useCallback(async()=>{setBusy(true);try{if(isPreview){const history=await salesRequest<SalesMapHistory>('/api/owner/sales-preview/map');setData(current=>current?mergePreviewMapHistory(current,history):current);}else{setData(await salesRequest<SalesWorkspace>('/api/salesman/bootstrap'));}setError('');}catch(e){setError(isPreview?'Unable to load full map history. Use Refresh to try again.':e instanceof Error?e.message:'Unable to refresh.');}finally{setBusy(false);}},[isPreview]);
  useEffect(()=>{void refresh();const timer=window.setInterval(()=>void refresh(),14*60*1000);return()=>window.clearInterval(timer);},[refresh]);
  useEffect(()=>{saveThemePreference(user.id,theme);document.documentElement.classList.toggle('dark',themeIsDark(theme));},[theme,user.id]);
  const today=isoToday();const due=data?.leads.filter(item=>item.followUpDate&&item.followUpDate<=today&&!['won','lost'].includes(item.status))??[];
  const events=useMemo(()=>{const end=new Date(`${today}T12:00:00Z`);end.setUTCDate(end.getUTCDate()+7);return [...(data?.notifications??[]),...(data?.leads??[]).filter(item=>item.followUpDate&&item.followUpDate<=end.toISOString().slice(0,10)&&!['won','lost'].includes(item.status)).map(item=>({id:`followup-${item.id}-${item.followUpDate}`,title:`${item.followUpDate<today?'Overdue follow-up':item.followUpDate===today?'Follow up today':'Upcoming follow-up'}: ${item.name}`,detail:`${item.followUpDate} - ${item.address}`,created_at:item.followUpDate}))];},[data,today]);
  const choose=(next:Tab)=>{setTab(next);setMenu(false);};
  const find=(job:Job)=>{setFocus({jobId:job.id,requestId:Date.now()});choose('map');};
  const newJob=(seed:Partial<SalesBooking>={})=>{setEditing(null);setBooking(seed);};
  const customer=(job:Job)=>data?.customers.find(item=>item.id===job.customerId);
  const filtered=data?.jobs.filter(job=>(status==='all'||job.status===status)&&`${customer(job)?.name} ${job.address} ${job.serviceType}`.toLowerCase().includes(search.toLowerCase()))??[];
  const upcoming=data?.jobs.filter(job=>job.date>=today&&!['completed','canceled'].includes(job.status)).sort((a,b)=>`${a.date} ${a.time}`.localeCompare(`${b.date} ${b.time}`))??[];
  const total=(states:string[])=>data?.commissions.filter(c=>states.includes(c.status)).reduce((sum,c)=>sum+c.amount,0)??0;
  const paidTotal=data?.statements.reduce((sum,statement)=>sum+statement.payments.reduce((subtotal,payment)=>subtotal+payment.amount,0),0)??0;
  return <div className="sales-shell min-h-screen bg-slate-100 text-ink dark:bg-slate-950 dark:text-white">
    {menu&&<button className="fixed inset-0 z-40 bg-black/50 lg:hidden" aria-label="Close menu" onClick={()=>setMenu(false)}/>}
    <aside className={`sidebar ${menu?'mobile-open':''}`}><div className="brand-card"><span className="text-sm text-cyan-200">The</span><h2 className="text-xl font-bold text-white">Powerwashing Pros</h2><p className="mt-2 text-sm text-slate-300">Salesman workspace</p></div><nav className="mt-5 space-y-1">{tabs.map(item=><button key={item.id} onClick={()=>choose(item.id)} className={`nav-item ${tab===item.id?'active':''}`}><item.icon size={19}/>{item.name}</button>)}</nav></aside>
    <div className="min-w-0">{isPreview&&<div className="sales-preview-banner"><span>Salesman preview - changes are not saved</span><button className="text-button shrink-0" onClick={onExitPreview}>Return to owner</button></div>}<header className="app-header"><div className="flex min-w-0 items-center justify-between gap-2"><div className="flex min-w-0 items-center gap-3"><button className="icon-button shrink-0 lg:hidden" title="Open menu" aria-label="Open menu" onClick={()=>setMenu(true)}><Menu size={19}/></button><div className="min-w-0"><p className="text-xs font-semibold uppercase text-lagoon">Salesman workspace</p><h1 className="text-xl font-bold text-ink dark:text-white">{tabs.find(item=>item.id===tab)?.name}</h1></div></div><div className="flex shrink-0 items-center gap-1"><SalesInbox events={events} preview={isPreview}/><button className="icon-button" title="Refresh" aria-label="Refresh" disabled={busy} onClick={()=>void refresh()}><RefreshCw size={18} className={busy?'animate-spin':''}/></button><ProfileMenu compact theme={theme} onTheme={setTheme} preview={isPreview} previewRole="salesman"/></div></div><p className="mt-2 text-sm text-slate-500">{isPreview?'Sample Salesman':user.name}</p></header>
    <main className="min-w-0 space-y-5 p-4 sm:p-6">{error&&<p role="alert" className="rounded-lg bg-rose-100 p-3 text-rose-700">{error}</p>}{data?.syncError&&<p role="status" className="rounded-lg bg-amber-50 p-3 text-sm text-amber-800 dark:bg-amber-500/10 dark:text-amber-200">Spreadsheet refresh unavailable. Showing the last saved records.</p>}{!data&&<p>{busy?'Loading your workspace...':'Workspace unavailable.'}</p>}
      {data&&tab==='dashboard'&&<><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Sales overview</h2><button className="primary-button gap-2" onClick={()=>newJob()}><Plus size={17}/>Book job</button></div><div className="grid grid-cols-2 gap-4 xl:grid-cols-3">{[
        ['Booked jobs',data.jobs.filter(j=>j.status!=='canceled').length],['Upcoming jobs',upcoming.length],['Follow-ups due',due.length],
        ['Estimated commission',currency.format(total(['estimated','pending']))],['Approved commission',currency.format(total(['approved']))],['Paid earnings',currency.format(paidTotal)],
      ].map(([name,value])=><div key={name} className="metric-card"><p className="text-sm text-slate-500">{name}</p><strong className="mt-2 block text-2xl">{value}</strong></div>)}</div><h3 className="text-lg font-semibold">Upcoming jobs</h3>{upcoming.map(job=><JobRow key={job.id} job={job} name={customer(job)?.name??'Customer'} onEdit={()=>{setEditing(job);setBooking({});}} onFind={()=>find(job)}/>)}{!upcoming.length&&<p className="text-slate-500">No upcoming jobs.</p>}</>}
      {data&&tab==='map'&&<Suspense fallback={<p>Loading map...</p>}><BusinessMap customers={data.mapCustomers} jobs={data.mapJobs} solicitations={data.solicitations} jobFocusRequest={focus}
        onAddJob={property=>newJob(property)} onSaveJobCoordinates={async()=>{}} onCreateSolicitation={async item=>{if(isPreview){setData(current=>current?savePreviewSolicitation(current,item):current);return;}await createSolicitation(item);await refresh();}}
        onUpdateSolicitation={async(id,patch)=>{if(isPreview){setData(current=>{const item=current?.solicitations.find(s=>s.id===id);return current&&item?savePreviewSolicitation(current,{...item,...patch},id):current;});return;}await saveSolicitationPatch(id,patch);await refresh();}} onDeleteSolicitation={async id=>{if(isPreview){setData(current=>current?removePreviewSolicitation(current,id):current);return;}await deleteSolicitation(id);await refresh();}}/></Suspense>}
      {data&&tab==='jobs'&&<><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-bold">My Jobs</h2><button className="primary-button gap-2" onClick={()=>newJob()}><Plus size={17}/>Book job</button></div><div className="flex flex-col gap-3 sm:flex-row"><label className="relative min-w-0 flex-1"><Search size={18} className="absolute left-3 top-5 text-slate-400"/><input type="search" className={`${input} pl-10`} aria-label="Search my jobs" placeholder="Search name or address" value={search} onChange={e=>setSearch(e.target.value)}/></label><select className={`${input} sm:max-w-48`} aria-label="Job status" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{['scheduled','in progress','completed','canceled','past due'].map(s=><option key={s}>{s}</option>)}</select></div>{filtered.map(job=><div key={job.id}><JobRow job={job} name={customer(job)?.name??'Customer'} onEdit={()=>{setEditing(job);setBooking({});}} onFind={()=>find(job)}/><div className="flex flex-wrap gap-3 px-3 py-2 text-sm">{customer(job)?.phone&&<a className="inline-flex gap-1 items-center text-lagoon" href={`tel:${customer(job)?.phone}`}><Phone size={15}/>Call</a>}{customer(job)?.phone&&<a className="text-lagoon" href={`sms:${customer(job)?.phone}`}>Text</a>}{customer(job)?.email&&<a className="inline-flex gap-1 items-center text-lagoon" href={`mailto:${customer(job)?.email}`}><Mail size={15}/>Email</a>}<span>{(()=>{const c=data.commissions.find(item=>item.jobId===job.id);return c?`${currency.format(c.servicePrice)} × ${formatRate(c.rate)} = ${currency.format(c.amount)} (${c.status})`:'';})()}</span></div></div>)}{!filtered.length&&<p className="text-slate-500">No jobs match.</p>}</>}
      {data&&tab==='leads'&&<><h2 className="text-xl font-bold">My follow-ups</h2>{data.leads.map(item=><article key={item.id} className="rounded-lg border border-slate-200 bg-white p-4 dark:border-slate-700 dark:bg-slate-900"><div className="flex flex-wrap justify-between gap-3"><div className="min-w-0"><h3 className="font-semibold break-words">{item.name}</h3><p className="text-sm break-words text-slate-500">{item.address}</p><p className="mt-2 text-sm">{item.followUpDate||'Not scheduled'} <span className={statusClass}>{['won','lost'].includes(item.status)?item.status:!item.followUpDate?'No date':item.followUpDate<today?'Overdue':item.followUpDate===today?'Today':'Upcoming'}</span></p><p className="mt-2 whitespace-pre-wrap break-words text-sm">{item.notes}</p></div>{!['won','lost'].includes(item.status)&&<div className="flex flex-wrap items-start gap-2"><button className="text-button gap-2" onClick={()=>setLead(item)}><Pencil size={15}/>Edit</button><button className="primary-button gap-2" onClick={()=>newJob({leadId:item.id,name:item.name==='Map follow-up'?'':item.name,address:item.address})}><Plus size={15}/>Book job</button></div>}</div></article>)}{!data.leads.length&&<p className="text-slate-500">No follow-ups yet.</p>}</>}
      {data&&tab==='earnings'&&<><h2 className="text-xl font-bold">My Earnings</h2>{data.commissions.map(c=><article key={c.id} className="rounded-lg border border-slate-200 bg-white p-4 dark:border-slate-700 dark:bg-slate-900"><div className="flex flex-wrap items-center justify-between gap-2"><strong>{c.customerName}</strong><span className={statusClass}>{c.status==='pending'?'Awaiting approval':c.status}</span></div><p className="mt-2">{currency.format(c.servicePrice)} × {formatRate(c.rate)} = <strong>{currency.format(c.amount)}</strong></p><p className="mt-1 text-sm text-slate-500">{c.jobDate}{c.paidAt?` · Paid ${c.paidAt.slice(0,10)}`:''}</p>{['approved','paid'].includes(c.status)&&c.currentServicePrice!==c.servicePrice&&<p className="mt-2 text-sm text-amber-600">Approved amount is locked; owner correction required for the changed price.</p>}{c.ownerNote&&<p className="mt-2 text-sm">{c.ownerNote}</p>}</article>)}{!data.commissions.length&&<p>No commissions yet.</p>}<EmployeePayrollStatements statements={data.statements}/></>}
    </main></div>
    {booking&&<SalesBookingForm seed={booking} job={editing} customer={editing?customer(editing):undefined} onSave={isPreview?async(input,job)=>{setData(current=>current?savePreviewSalesBooking(current,input,job):current);}:undefined} onClose={()=>{setBooking(null);setEditing(null);}} onSaved={async()=>{setBooking(null);setEditing(null);await refresh();choose('jobs');}}/>}
    {lead&&<SalesLeadForm lead={lead} onSave={isPreview?async item=>{setData(current=>current?savePreviewSalesLead(current,item):current);}:undefined} onClose={()=>setLead(null)} onSaved={async()=>{setLead(null);await refresh();}}/>}
  </div>;
}
function JobRow({job,name,onEdit,onFind}:{job:Job;name:string;onEdit:()=>void;onFind:()=>void}){return <article className="rounded-lg border border-slate-200 bg-white p-4 dark:border-slate-700 dark:bg-slate-900"><div className="flex flex-wrap justify-between gap-3"><div className="min-w-0"><strong className="break-words">{name}</strong><p className="mt-1 text-sm text-slate-500">{job.date} at {job.time} · {job.status}</p><p className="mt-1 break-words text-sm">{job.address} · {job.serviceType} · {currency.format(job.price)}</p>{job.employeeInstructions&&<p className="mt-2 break-words text-sm text-slate-500">{job.employeeInstructions}</p>}</div><div className="flex items-start gap-2"><button className="icon-button" title="Find on map" aria-label={`Find ${name} on map`} onClick={onFind}><MapPinned size={17}/></button>{canEdit(job)&&<button className="icon-button" title="Edit job" aria-label={`Edit ${name}`} onClick={onEdit}><Pencil size={17}/></button>}</div></div></article>;}
function SalesBookingForm({seed,job,customer,onSave,onClose,onSaved}:{seed:Partial<SalesBooking>;job:Job|null;customer?:{name:string;phone:string;email:string};onSave?:(input:SalesBooking,job:Job|null)=>Promise<void>;onClose:()=>void;onSaved:()=>Promise<void>}){
  const {user}=useAuth();const storageKey=`powerwash-pending-sales-booking:${user.id}`;
  const [pending]=useState<SalesBooking|null>(()=>{if(job||onSave)return null;try{return JSON.parse(localStorage.getItem(storageKey)??'null');}catch{return null;}});
  const [draft,setDraft]=useState({name:customer?.name??'',phone:customer?.phone??'',email:customer?.email??'',address:job?.address??'',serviceType:job?.serviceType??'',date:job?.date??isoToday(),time:job?.time??'09:00',employeeInstructions:job?.employeeInstructions??'',latitude:job?.latitude,longitude:job?.longitude,...seed,...(pending??{})});
  const [price,setPrice]=useState(job?String(job.price):pending?String(pending.price):'');const [requestId]=useState(()=>pending?.requestId??crypto.randomUUID());const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const [attempt,setAttempt]=useState<SalesBooking|null>(pending);
  function changeField(key:string,value:string){setDraft(current=>({...current,[key]:value,...(key==='address'&&value!==current.address?{latitude:undefined,longitude:undefined}:{})}));}
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{
    const payload=attempt??{...draft,price:Number(price),...(job?draft.address!==job.address?{latitude:null,longitude:null}:{}:{requestId})};
    if(onSave){await onSave(payload as SalesBooking,job);}else{
      if(!job){setAttempt(payload as SalesBooking);localStorage.setItem(storageKey,JSON.stringify(payload));}
      await salesRequest(`/api/salesman/jobs${job?`/${job.id}`:''}`,job?'PATCH':'POST',payload);if(!job)localStorage.removeItem(storageKey);
    }await onSaved();
  }catch(err){if((err as {status?:number}).status===400&&!job&&!onSave){setAttempt(null);localStorage.removeItem(storageKey);}setError(err instanceof Error?err.message:'Unable to book job.');}finally{setBusy(false);}}
  return <div className="sales-modal"><form onSubmit={submit} className="sales-dialog">
    <div className="flex justify-between gap-3"><h2 className="text-xl font-bold">{job?'Edit booking':'Book a job'}</h2><button type="button" className="icon-button" title="Close" aria-label="Close booking" disabled={busy} onClick={onClose}><X size={18}/></button></div>
    {attempt&&<p role="status" className="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-800">This booking is awaiting confirmation.</p>}
    <fieldset disabled={busy||Boolean(attempt)} className="settings-grid mt-5">
      {[['name','Customer name','text'],['phone','Phone','tel'],['email','Email','email'],['address','Address','text'],['serviceType','Service','text'],['date','Date','date'],['time','Time','time']].map(([key,label,type])=><label key={key} className="block min-w-0 text-sm font-semibold">{label}<input className={input} type={type} required={!['phone','email'].includes(key)} value={String(draft[key as keyof typeof draft]??'')} onChange={e=>changeField(key,e.target.value)}/></label>)}
      <label className="block min-w-0 text-sm font-semibold">Service price<input className={input} required type="number" min="0" max="100000" step="0.01" inputMode="decimal" value={price} placeholder="0.00" onChange={e=>setPrice(e.target.value)}/></label>
      <label className="block min-w-0 text-sm font-semibold sm:col-span-2">Instructions for employee<textarea className={`${input} min-h-24`} value={draft.employeeInstructions} onChange={e=>changeField('employeeInstructions',e.target.value)}/></label>
    </fieldset>
    <p className="mt-4 text-sm text-lagoon">Estimated commission: {currency.format(Number(price||0)*0.20)}</p>
    {error&&<p role="alert" className="mt-3 rounded-lg bg-rose-100 p-3 text-sm text-rose-700">{error}</p>}
    <div className="mt-5 flex flex-wrap justify-end gap-2"><button type="button" className="text-button" disabled={busy} onClick={onClose}>Cancel</button><button className="primary-button gap-2" disabled={busy}><Save size={16}/>{busy?'Saving...':attempt?'Retry same booking':job?'Save changes':'Book job'}</button></div>
  </form></div>;
}
function SalesLeadForm({lead,onSave,onClose,onSaved}:{lead:Lead;onSave?:(lead:Lead)=>Promise<void>;onClose:()=>void;onSaved:()=>Promise<void>}){const [draft,setDraft]=useState(lead);const [error,setError]=useState('');const [busy,setBusy]=useState(false);return <div className="sales-modal"><form className="sales-dialog" onSubmit={async e=>{e.preventDefault();setBusy(true);try{if(onSave)await onSave(draft);else await salesRequest(`/api/salesman/leads/${lead.id}`,'PATCH',{name:draft.name,contact:draft.contact,notes:draft.notes,followUpDate:draft.followUpDate,status:draft.status});await onSaved();}catch(err){setError(err instanceof Error?err.message:'Unable to save.');}finally{setBusy(false);}}}><div className="flex justify-between"><h2 className="text-xl font-bold">Edit follow-up</h2><button type="button" className="icon-button" title="Close" aria-label="Close follow-up" onClick={onClose}><X size={18}/></button></div><div className="mt-4 space-y-3">{[['name','Name','text'],['contact','Contact','text'],['followUpDate','Follow-up date','date']].map(([key,label,type])=><label className="block text-sm font-semibold" key={key}>{label}<input className={input} type={type} value={draft[key as 'name'|'contact'|'followUpDate']} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}<label className="block text-sm font-semibold">Status<select className={input} value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as Lead['status']})}>{['new','contacted','quoted','lost'].map(s=><option key={s}>{s}</option>)}</select></label><label className="block text-sm font-semibold">Notes<textarea className={input} value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label></div>{error&&<p role="alert" className="mt-3 text-rose-600">{error}</p>}<button className="primary-button mt-4 w-full gap-2" disabled={busy}><Save size={17}/>{busy?'Saving...':'Save follow-up'}</button></form></div>;}
function SalesInbox({events,preview=false}:{events:SalesNotification[];preview?:boolean}){
  const {user}=useAuth();const [open,setOpen]=useState(false);const [read,setRead]=useState<string[]>([]);const [error,setError]=useState('');
  useEffect(()=>{if(preview)return;void loadReadNotificationKeys().then(r=>setRead(r?.readKeys??[])).catch(()=>setError('Unable to load inbox state.'));},[user.id,preview]);
  const key=(e:SalesNotification)=>`sales|${e.id}`;const unseen=events.filter(e=>!read.includes(`inbox-seen|${key(e)}`));
  async function mark(keys:string[]){if(preview){setRead(current=>[...new Set([...current,...keys])]);return;}try{const result=await markNotificationsRead(keys);if(!result)throw new Error('Inbox unavailable');setRead(result.readKeys);}catch{setError('Unable to save inbox state.');}}
  return <><button className="icon-button relative" title="Notifications" aria-label="Notifications" onClick={()=>{setOpen(!open);if(!open&&unseen.length)void mark(unseen.map(e=>`inbox-seen|${key(e)}`));}}><Bell size={18}/>{unseen.length>0&&<span className="absolute right-0 top-0 h-2.5 w-2.5 rounded-full bg-rose-500"/>}</button>{open&&<><button className="fixed inset-0 z-40 bg-black/20" aria-label="Close notifications" onClick={()=>setOpen(false)}/><section className="sales-inbox"><div className="flex justify-between items-center"><h2 className="font-bold">Notifications</h2><button className="icon-button" title="Close" aria-label="Close inbox" onClick={()=>setOpen(false)}><X size={17}/></button></div>{error&&<p role="alert" className="text-sm text-rose-600">{error}</p>}<div className="mt-3 space-y-2">{events.map(e=><article key={e.id} className={`flex gap-3 rounded-lg border p-3 ${read.includes(key(e))?'opacity-60':'border-lagoon'}`}><div className="min-w-0 flex-1"><strong className="block text-sm break-words">{e.title}</strong><p className="mt-1 text-xs break-words text-slate-500">{e.detail}</p></div><button className="icon-button shrink-0" disabled={read.includes(key(e))} title="Mark as read" aria-label={`Mark ${e.title} as read`} onClick={()=>void mark([key(e)])}><Check size={15}/></button></article>)}{!events.length&&<p className="text-sm text-slate-500">Your inbox is clear.</p>}</div></section></>}</>;
}
